#Install and load the packages

#Bioconductor packages
install.packages("BiocManager")
library(BiocManager)

BiocManager::install("biomaRt")
BiocManager::install("clusterProfiler")
BiocManager::install("msigdbr")
BiocManager::install("cytolib")
BiocManager::install("org.Hs.eg.db", character.only = TRUE)

library(biomaRt)
library(msigdbr)
library(org.Hs.eg.db)
library(clusterProfiler)
library(corto)
library(cytolib)

#CRAN packages
install.packages("BH")
install.packages("devtools")
install.packages("Matrix")
install.packages("circlize")
install.packages("RColorBrewer")
install.packages("plotly")
install.packages("janitor")
install.packages("ggsci")
install.packages("patchwork")
install.packages("ggthemes")
install.packages("here")
install.packages("readxl")
install.packages("scales")
install.packages("tidyverse")
install.packages("flexdashboard")
install.packages("vegan")
install.packages("DT")
install.packages("heatmaply")

library("BH")
library("devtools")
library("Matrix")
library("circlize")
library("RColorBrewer")
library("plotly")
library("janitor")
library("ggsci")
library("patchwork")
library("ggthemes")
library("here")
library("readxl")
library("scales")
library("tidyverse")
library("flexdashboard")
library("vegan")
library("DT")
library("heatmaply")